# Generated by Django 4.0.5 on 2022-09-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Act', 'Active'), ('Arc', 'Archive')], max_length=50)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.assembly')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('part_of_assembly', models.ManyToManyField(through='search.Counter', to='search.assembly')),
            ],
        ),
        migrations.AddField(
            model_name='counter',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.detail'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='part_of_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.product'),
        ),
    ]
